//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pakisaadetiste_haldur.wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pakisaadetiste_haldur.wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kas soovid kindlasti selle saadetise kustutada?.
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinnitus.
        /// </summary>
        public static string Confirm_Title {
            get {
                return ResourceManager.GetString("Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palun vali sihtlinn.
        /// </summary>
        public static string Err_CityRequired {
            get {
                return ResourceManager.GetString("Err_CityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palun vali tarneviis.
        /// </summary>
        public static string Err_DeliveryRequired {
            get {
                return ResourceManager.GetString("Err_DeliveryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palun vali nimekirjast rida, mida kustutada.
        /// </summary>
        public static string Err_NoSelection {
            get {
                return ResourceManager.GetString("Err_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palun vali saadetise liik.
        /// </summary>
        public static string Err_PackageTypeRequired {
            get {
                return ResourceManager.GetString("Err_PackageTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viga.
        /// </summary>
        public static string Err_Title {
            get {
                return ResourceManager.GetString("Err_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaal peab olema number.
        /// </summary>
        public static string Err_WeightInvalid {
            get {
                return ResourceManager.GetString("Err_WeightInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kustuta.
        /// </summary>
        public static string Str_ButtonDelete {
            get {
                return ResourceManager.GetString("Str_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saada.
        /// </summary>
        public static string Str_ButtonSend {
            get {
                return ResourceManager.GetString("Str_ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvesta.
        /// </summary>
        public static string Str_ButtonUpdate {
            get {
                return ResourceManager.GetString("Str_ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadress.
        /// </summary>
        public static string Str_LabelAddress {
            get {
                return ResourceManager.GetString("Str_LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linn.
        /// </summary>
        public static string Str_LabelCity {
            get {
                return ResourceManager.GetString("Str_LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarneviis.
        /// </summary>
        public static string Str_LabelDelivery {
            get {
                return ResourceManager.GetString("Str_LabelDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sihtkoht.
        /// </summary>
        public static string Str_LabelDestination {
            get {
                return ResourceManager.GetString("Str_LabelDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saadetise liik.
        /// </summary>
        public static string Str_LabelPackageType {
            get {
                return ResourceManager.GetString("Str_LabelPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hind.
        /// </summary>
        public static string Str_LabelPrice {
            get {
                return ResourceManager.GetString("Str_LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaal.
        /// </summary>
        public static string Str_LabelWeight {
            get {
                return ResourceManager.GetString("Str_LabelWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.00.
        /// </summary>
        public static string Str_PriceDefault {
            get {
                return ResourceManager.GetString("Str_PriceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täida andmed ja saadame sinu paki..
        /// </summary>
        public static string Str_RegisterSubtitle {
            get {
                return ResourceManager.GetString("Str_RegisterSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreeri saadetis.
        /// </summary>
        public static string Str_RegisterTitle {
            get {
                return ResourceManager.GetString("Str_RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saadetud pakid.
        /// </summary>
        public static string Str_SentPackagesTitle {
            get {
                return ResourceManager.GetString("Str_SentPackagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakisaadetiste haldur.
        /// </summary>
        public static string Str_WindowTitle {
            get {
                return ResourceManager.GetString("Str_WindowTitle", resourceCulture);
            }
        }
    }
}
