//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pakisaadetiste_haldur.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pakisaadetiste_haldur.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palun sisesta aadress.
        /// </summary>
        public static string Err_AddressRequired {
            get {
                return ResourceManager.GetString("Err_AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaal ei tohi olla suurem kui 100 kg.
        /// </summary>
        public static string Err_MaksimaalneKaal {
            get {
                return ResourceManager.GetString("Err_MaksimaalneKaal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadress ei tohi olla pikem kui 100 märki.
        /// </summary>
        public static string Err_MaxAddressLength {
            get {
                return ResourceManager.GetString("Err_MaxAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadress peab sisaldama vähemalt 3 märki.
        /// </summary>
        public static string Err_MinAddressLength {
            get {
                return ResourceManager.GetString("Err_MinAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saadetis puudub.
        /// </summary>
        public static string Err_SaadetisPuudub {
            get {
                return ResourceManager.GetString("Err_SaadetisPuudub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tundmatu saadetise liik.
        /// </summary>
        public static string Err_UnknownLiik {
            get {
                return ResourceManager.GetString("Err_UnknownLiik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tundmatu linn.
        /// </summary>
        public static string Err_UnknownLinn {
            get {
                return ResourceManager.GetString("Err_UnknownLinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tundmatu tarneviis.
        /// </summary>
        public static string Err_UnknownTarneviis {
            get {
                return ResourceManager.GetString("Err_UnknownTarneviis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaal peab olema number.
        /// </summary>
        public static string Err_WeightInvalid {
            get {
                return ResourceManager.GetString("Err_WeightInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaal peab olema suurem kui null.
        /// </summary>
        public static string Err_WeightPositive {
            get {
                return ResourceManager.GetString("Err_WeightPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaal peab olema suurem kui 0 kg.
        /// </summary>
        public static string Err_WeightRequired {
            get {
                return ResourceManager.GetString("Err_WeightRequired", resourceCulture);
            }
        }
    }
}
